on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
      path:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ArgoCD Repo
        uses: actions/checkout@v4
        with:
          repository: raf555/argocd
          token: ${{ secrets.DEPLOYMENT_TOKEN }}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update Image Tag
        run: |
          cd ${{ inputs.path }}
          kustomize edit set image "${{ inputs.image_name }}=*:${{ inputs.tag }}"
        # kustomize edit set image ${{ inputs.image_name }}=ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:${{ inputs.tag }}

      - name: Commit
        id: commit_step
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "deploy(${{ inputs.path }}): update ${{ inputs.image_name }} to ${{ inputs.tag }}"
            echo "committed=true" >> $GITHUB_OUTPUT
          else
            echo "committed=false" >> $GITHUB_OUTPUT
          fi

      - name: Push
        if: steps.commit_step.outputs.committed == 'true'
        uses: cutlerydrawer/action-git-try-push@v2
        with:
          branch: main
          tries: 10
